/RMG/Manager/Randomization/Seed {SEED}

/RMG/Geometry/RegisterDetectorsFromGDML Germanium
/RMG/Geometry/RegisterDetectorsFromGDML Scintillator
/RMG/Geometry/GDMLDisableOverlapCheck

# name tables with ntuple
/RMG/Output/NtupleUseVolumeName true

# physics options
/RMG/Processes/EnableGammaAngularCorrelation true

/run/initialize

# store everything in single precision
/RMG/Output/Germanium/StoreSinglePrecisionPosition
/RMG/Output/Germanium/StoreSinglePrecisionEnergy
/RMG/Output/Scintillator/StoreSinglePrecisionPosition
/RMG/Output/Scintillator/StoreSinglePrecisionEnergy
/RMG/Output/Vertex/StoreSinglePrecisionPosition

# drop deferred (e.g. optical photon) tracks if no energy in germanium
/RMG/Output/Germanium/DiscardWaitingTracksUnlessGermaniumEdep

# do not store events with no energy deposition in germanium
/RMG/Output/Germanium/EdepCutLow 1 eV

# store trackid
/RMG/Output/Germanium/StoreTrackID true
/RMG/Output/Scintillator/StoreTrackID true

$GENERATOR

$CONFINEMENT
/RMG/Generator/Confinement/MaxSamplingTrials 1000000

/run/beamOn {N_EVENTS}
